# Generated by Django 4.2.3 on 2023-07-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
